package com.chetiwen.common;

public class LogType {

    public static final String CLIENT_CHECKVIN_REQUEST ="CLIENT_CHECKVIN_REQUEST";
    public static final String CLIENT_QUERYVIN_REQUEST ="CLIENT_QUERYVIN_REQUEST";
    public static final String CLIENT_GETORDER_REQUEST ="CLIENT_GETORDER_REQUEST";
    public static final String CLIENT_ORDERREP_REQUEST ="CLIENT_ORDERREP_REQUEST";
    public static final String CLIENT_BALANCE_REQUEST ="CLIENT_BALANCE_REQUEST";

    public static final String ANTQUEEN_CALLBACK ="ANTQUEEN_CALLBACK";
    public static final String ANTQUEEN_CHECKVIN_REQUEST ="ANTQUEEN_CHECKVIN_REQUEST";
    public static final String ANTQUEEN_CHECKVIN_RESPONSE ="ANTQUEEN_CHECKVIN_RESPONSE";
    public static final String ANTQUEEN_QUERYVIN_REQUEST ="ANTQUEEN_QUERYVIN_REQUEST";
    public static final String ANTQUEEN_QUERYVIN_RESPONSE ="ANTQUEEN_QUERYVIN_RESPONSE";
    public static final String ANTQUEEN_GETORDER_REQUEST ="ANTQUEEN_GETORDER_REQUEST";
    public static final String ANTQUEEN_GETORDER_RESPONSE ="ANTQUEEN_GETORDER_RESPONSE";
    public static final String ANTQUEEN_ORDERREP_REQUEST ="ANTQUEEN_ORDERREP_REQUEST";
    public static final String ANTQUEEN_ORDERREP_RESPONSE ="ANTQUEEN_ORDERREP_RESPONSE";
    public static final String ANTQUEEN_BALANCE_REQUEST ="ANTQUEEN_BALANCE_REQUEST";


    public static final String QUCENT_CALLBACK ="QUCENT_CALLBACK";
    public static final String QUCENT_QUERYVIN_REQUEST ="QUCENT_QUERYVIN_REQUEST";
}
